.eslintrc.cjs, package-lock.json, package.json, src/App.tsx, src/AppSuspense.tsx, src/app/app.route.ts, src/app/core/auth/Auth.tsx, src/app/core/auth/auth.routes.ts, src/app/core/auth/containers/Login.tsx, src/app/core/auth/containers/Register.tsx, src/app/core/modules/custom-router-dom/PrivateRoute.tsx, src/app/core/modules/custom-router-dom/RouterOutlet.tsx, src/app/core/modules/custom-router-dom/index.ts, src/app/core/modules/custom-router-dom/router.interface.ts
=> [Initial Base] Config router paths

src/shared/components/InputField.tsx, src/stylesheet/base/_reset.scss, src/stylesheet/base/_variables.scss, src/stylesheet/modules/_all.scss, src/stylesheet/modules/_input-field.scss
- [Sprint backlog URL](https://docs.google.com/spreadsheets/d/15HwUJ5TIas9ywzYUvKoW8NMbrCrGb9qP/edit#gid=1890329971)
- Task: Create Modules UI
- Create Modules UI
=> [Task] - Add component input

.eslintrc.cjs, package-lock.json, package.json, src/app/core/helpers/authHelper.ts, src/app/core/helpers/jwtHelper.ts, src/app/core/helpers/storageHelper.ts, src/app/core/services/api.service.ts, src/app/core/services/authStorage.service.ts, src/config/endpoint.ts, src/config/environment.ts
=> [Setup API Service] Setup api services

src/App.tsx, src/stylesheet/layout/_header.scss
- Fix header stylesheet import
=> [Feature] Fix header style file import

package-lock.json, package.json, src/app/core/auth/containers/Register.tsx, src/app/shared/components/InputField.tsx, src/app/shared/components/index.tsx, src/stylesheet/base/_variables.scss, src/stylesheet/modules/_button.scss, src/stylesheet/modules/_input-field.scss, src/stylesheet/pages/_register.scss
- [Sprint backlog URL](https://docs.google.com/spreadsheets/d/15HwUJ5TIas9ywzYUvKoW8NMbrCrGb9qP/edit#gid=1890329971)
- Task: Validate Register Form
- Add Validate Register Form
=> [Task] - Validate Register Form

src/app/core/auth/auth.reducers.ts, src/app/core/auth/containers/Login.tsx, src/app/core/helpers/jwtHelper.ts, src/config/endpoint.ts
- Handle error and loading for login
=> [Feature] Handle error and loading for login

package-lock.json, package.json, src/app/core/auth/containers/Login.tsx, src/app/shared/components/InputGroup.tsx, src/stylesheet/base/_variables.scss
- [Sprint backlog URL](https://docs.google.com/spreadsheets/d/15HwUJ5TIas9ywzYUvKoW8NMbrCrGb9qP/edit#gid=1890329971)
- Task: Validate Login Form
- Add Validate Login Form
=> [Task] - Validate for login form

src/App.tsx, src/app/app.route.ts, src/app/pages/Page.tsx, src/app/pages/articles/article.routes.ts, src/app/pages/articles/containers/ArticleDetail.tsx, src/app/pages/articles/containers/ArticleList.tsx, src/app/pages/articles/containers/Articles.tsx, src/app/pages/home/containers/Home.tsx, src/app/pages/home/home.routes.ts, src/app/pages/page.routes.ts, src/app/pages/user/containers/UserDetail.tsx, src/app/pages/user/containers/UserList.tsx, src/app/pages/user/containers/Users.tsx, src/app/pages/user/user.routes.ts
- Config Router for Home
- Config Router for Articles
- Config Router for Users
=> [Feature] Config router for pages

src/App.tsx, src/app/shared/components/Footer.tsx, src/app/shared/components/Header.tsx, src/app/shared/components/Post.tsx, src/app/shared/components/index.tsx
=> [Feature] Modify header link and file import

src/app/core/auth/containers/Register.tsx, src/config/endpoint.ts
=> [Feature] - Apply api register

src/app/pages/home/containers/components/PublicPost.tsx, src/app/pages/home/containers/components/ScrollToTopButton.tsx, src/assets/icons/ic-arrow-up.svg, src/config/endpoint.ts, src/stylesheet/modules/_icon.scss, src/stylesheet/pages/_home.scss, src/stylesheet/states/_state.scss
- [Sprint backlog URL](https://docs.google.com/spreadsheets/d/15HwUJ5TIas9ywzYUvKoW8NMbrCrGb9qP/edit#gid=1890329971)
- Task: Add Load more button
- Add Load more button
=> [Feature] - Add Load more button for List post

src/app/core/auth/auth.reducers.ts, src/app/core/auth/containers/Login.tsx, src/app/core/helpers/authHelper.ts, src/app/shared/components/Spinner.tsx, src/app/shared/components/index.tsx, src/stylesheet/pages/_signin.scss, src/stylesheet/states/_all.scss, src/stylesheet/states/_color.scss, src/stylesheet/states/_text.scss
=> [Feature] Add loadding and errror UI

src/app/core/auth/containers/Register.tsx, src/app/shared/components/Spinner.tsx, src/app/shared/components/index.tsx, src/stylesheet/modules/_spinner.scss, src/stylesheet/pages/_register.scss
- Add loading and handle error
=> [Task] Add loading and handle error

src/app/core/auth/containers/Login.tsx, src/app/core/auth/containers/Register.tsx, src/app/core/helpers/jwtHelper.ts, src/app/core/services/auth.service.ts, src/app/pages/Page.tsx
=> [Features] Logout went cookies expired

.gitignore, src/app/shared/components/PostList.tsx
- Config for deployment on netlify 
- Fix convention for build files
=> [Deloyment] Config for deployment

src/app/core/auth/containers/Register.tsx, src/app/shared/utils/formatDate.ts
=> [Fix bug] - Fix validate date

src/app/pages/Page.tsx
- Fix handle signout and redirect pages
=> [Fix bug] Fix handle signout and redirect

index.html, src/app/app.route.ts, src/app/core/modules/custom-router-dom/RouterOutlet.tsx
- Fix bug can redirect to login from home page after login
=> [Fix Bug] Can redirect to login from home page after login

src/app/core/modules/custom-router-dom/RouterOutlet.tsx, src/app/shared/components/Header.tsx
- Fix bug cant login after logout
=> [Fix bug] Cant login after logout

src/app/shared/components/Comment.tsx, src/app/shared/components/ListComments.tsx, src/stylesheet/base/_reset.scss, src/stylesheet/modules/_all.scss, src/stylesheet/modules/_comment.scss, src/stylesheet/modules/_list-comments.scss
=> [Task] - Add List Comments UI

src/app/pages/articles/article.routes.ts, src/app/pages/articles/containers/ArticleDetail.tsx, src/app/shared/components/Comment.tsx, src/app/shared/components/ListComments.tsx, src/app/shared/components/Post.tsx, src/app/shared/components/Sidebar.tsx, src/stylesheet/modules/_comment.scss, src/stylesheet/modules/_list-comments.scss
=> [Task] Call api get list comments

src/app/pages/articles/containers/ArticleDetail.tsx, src/app/shared/components/PopularPostSkeleton.tsx, src/app/shared/components/Sidebar.tsx, src/app/shared/components/index.tsx, src/stylesheet/layout/_sidebar.scss, src/stylesheet/modules/_post.scss, src/stylesheet/modules/_short-info.scss, src/stylesheet/pages/_articles.scss
=> [PBI4][Modify] Modify sidebar

src/app/shared/components/Comment.tsx, src/app/shared/components/ListComments.tsx, src/stylesheet/modules/_comment.scss
=> [Feature] Add comment input ui

src/app/core/helpers/jwtHelper.ts, src/app/pages/articles/containers/ArticleDetail.tsx, src/app/pages/user/containers/UserDetail.tsx, src/app/pages/user/containers/components/UserProfile.tsx, src/app/shared/components/Post.tsx, src/app/shared/components/PostList.tsx, src/stylesheet/modules/_user-profile.scss
=> [Task] Apply api get user info
